/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/env.d.ts` (hash: d7380b711d78ca61aefd9fcfc88c6e54)
interface __BaseEnv_Env {
	GEOSITE_BUCKET: R2Bucket;
	UPSTREAM_YAML_URL: "https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat_plain.yml";
	UPSTREAM_USER_AGENT: "surge-geosite-worker/2";
	SRS_UPSTREAM_BASE_URL: "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set";
	SRS_UPSTREAM_USER_AGENT: "surge-geosite-worker/2";
	SRS_CACHE_TTL_SECONDS: "86400";
	MRS_UPSTREAM_BASE_URL: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite";
	MRS_UPSTREAM_USER_AGENT: "surge-geosite-worker/2";
	MRS_CACHE_TTL_SECONDS: "86400";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "UPSTREAM_YAML_URL" | "UPSTREAM_USER_AGENT" | "SRS_UPSTREAM_BASE_URL" | "SRS_UPSTREAM_USER_AGENT" | "SRS_CACHE_TTL_SECONDS" | "MRS_UPSTREAM_BASE_URL" | "MRS_UPSTREAM_USER_AGENT" | "MRS_CACHE_TTL_SECONDS">> {}
}
